global:
  scrape_interval: 15s

scrape_configs:
  
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['{{srv}}:9090']


  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['{{srv}}:9100']

